# Generated by Django 4.1 on 2024-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_post_like_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="age",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
