# Generated by Django 4.1 on 2024-04-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_post_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
