# Generated by Django 4.1 on 2024-04-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_post_image_post_media"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="media",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
