# Generated by Django 4.1 on 2024-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_post_media_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="pinned", field=models.BooleanField(default=False),
        ),
    ]
