# Generated by Django 4.1 on 2024-05-04 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_post_duedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="duedate",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 4, 16, 51, 57, 572899), null=True
            ),
        ),
    ]
