# Generated by Django 4.1 on 2024-05-05 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_post_duedate"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="duedate",),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 5, 14, 21, 22, 612904), null=True
            ),
        ),
    ]
