# Generated by Django 4.1 on 2024-05-08 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_notification_post_alter_post_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="post",),
        migrations.RemoveField(model_name="notification", name="read",),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 9, 8, 30, 1, 373465), null=True
            ),
        ),
    ]
